# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates cosine similarity matrix for a given matix
#'
#' @description Tranforms product hits matrix to product similarity matrix
#' @param x matrix of prouct hits
#' @return matrix of product similarity
cosineCpp <- function(x) {
    .Call('_recommender_cosineCpp', PACKAGE = 'recommender', x)
}

